In [1]:
import torch

In [2]:
T = torch.Tensor([1])

In [3]:
T

tensor([1.])

In [4]:
U = torch.Tensor([2])

In [5]:
U

tensor([2.])

In [6]:
T + U

tensor([3.])

In [7]:
T * U

tensor([2.])

In [8]:
import numpy as np

In [9]:
N = np.array([1,2,3.5])

In [10]:
N

array([1. , 2. , 3.5])

In [12]:
P = torch.Tensor(N)

In [13]:
P

tensor([1.0000, 2.0000, 3.5000])

In [14]:
U * P

tensor([2., 4., 7.])

In [15]:
2 * P

tensor([2., 4., 7.])

In [16]:
torch.log2(P)

tensor([0.0000, 1.0000, 1.8074])

In [18]:
abc = torch.Tensor([1,2,3.5])

In [20]:
abc.requires_grad=True

In [21]:
abc

tensor([1.0000, 2.0000, 3.5000], requires_grad=True)

In [22]:
efg = torch.Tensor([7,8,9.6])
efg.requires_grad=True

In [23]:
efg

tensor([7.0000, 8.0000, 9.6000], requires_grad=True)

In [25]:
hij = abc + efg

In [26]:
hij

tensor([ 8.0000, 10.0000, 13.1000], grad_fn=<AddBackward0>)

In [27]:
klm = torch.log2(hij)

In [28]:
klm

tensor([3.0000, 3.3219, 3.7115], grad_fn=<Log2Backward>)

In [31]:
nop = klm.sum()

In [32]:
nop

tensor(10.0334, grad_fn=<SumBackward0>)

In [33]:
nop.backward()

In [35]:
efg.grad

tensor([0.1803, 0.1443, 0.1101])

In [36]:
hij.grad